[package]
name = "uni-gl-example"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "basic.rs"

[dependencies]
uni-app = "0.2.*"
uni-gl = { path = ".." }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.83"
